# Generated by Django 3.0.8 on 2020-07-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_auto_20200720_0356'),
        ('editorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('authors', models.ManyToManyField(to='authors.Author')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorials.Editorial')),
            ],
        ),
    ]
