# Generated by Django 3.0.8 on 2020-07-20 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_pub',
            field=models.DateField(default=datetime.datetime(2020, 7, 20, 10, 56, 6, 152205, tzinfo=utc), verbose_name='Publication date'),
        ),
    ]
